### ISSUE TITLE
Präsentation zum Roboter für Klasse erstellen

### ISSUE THREAD

**Issue by Al3xAda** [Lorenzuser/Projekt--HomeDirect#36]

**Comment by Al3xAda** [comment]
@Lorenzuser Womit wollen wir die Presentation machen?

- [x] PowerPoint 
- [ ] Keynote
- [ ] Google Slides 
- [ ] Libre Office

**Comment by Lorenzuser** [comment]
Powerpoint ist doch ziemlich gut, auch mit dem Freigeben zwischen Geräten. Außerdem müssen wir auch nichts dafür bezahlen, da wir Schüler sind...

**Comment by Al3xAda** [comment]
Präsi: https://hgoolde-my.sharepoint.com/:p:/g/personal/alexander_janzen_hgo-ol_de/Eb2pOoR9oD1JvF4gikUfFGQBlBBOJnjkCurdM9Lc2bGvww
